<?php

  /**
   * @var \Mageplaza\HelloWorld\Block\Display $block
   */

  // $result = $block->getCategories();
  // echo "<div class='menu-categories'>";
  // foreach ($result as $key => $value) {
  //   // $arr[3] will be updated with each value from $arr...
  //   echo "<button class = 'dropdown-toggle' id_cat='{$key}'>" 
  //   .  "{$value}" 
  //   . "</button>";
  // }
  // echo "</div>";

  // foreach ($result as $key => $value) {
  //   echo "<div class = 'lnt-dropdown-mega-menu' id_cat_block='{$key}' style = 'display: none' >block info - {$value}</div>";
  // }
?>


