<?php
  /**
   * @var \Qdigital\Theme\Block\Categories $block
   */
  $categories = $block->getCategories(2);
  $subCategories = $block->getCategories(3);
  $products = $block->getProducts();
?>

<!-- menu categories -->
<div class='menu-categories'>
  <?php foreach ($categories as $id => $category):?>
    <a class ='dropdown-toggle' id_cat='<?=$id?>'>
      <?= $category->getName() ?> 
    </a>
  <?php endforeach;?>
</div>



<!-- modal category -->
<div class = 'lnt-dropdown-mega-menu' style='display: none'>
  <!-- menu sub categories -->
  <div class='lnt-category'>
    <ui>
      <?php foreach ($subCategories as $id => $subCategory): ?>
          <li class='subCategory' parent_cat_id='<?= $subCategory->getParentCategory()->getId();?>' cat_id='<?= $subCategory->getId()?>'><a><?=$subCategory->getName()?></a></li>
      <?php endforeach;?>
    </ui>
  </div>
  <!-- products container -->
  <div class='product-list'>
    <?php foreach($products as $id => $product):?>
      <?php $idsCategory = $product->getCategoryIds()?>
      <div class='product<?php foreach($idsCategory as $idCategory){
                            echo ' id-sub-category-'.$idCategory;
                          }?>'>

        <?php
        $objectManager =\Magento\Framework\App\ObjectManager::getInstance();
        $helperImport = $objectManager->get('\Magento\Catalog\Helper\Image');
      
        $imageUrl = $helperImport->init($product, 'product_page_image_small')
                        ->setImageFile($product->getSmallImage()) // image,small_image,thumbnail
                        ->resize(380)
                        ->getUrl();
        ?>
        <div><?= $product->getName()?></div>
        <div calss='produc-img-container'><img class= 'product-img' src="<?= $imageUrl?>"></img></div>
        <ui>
          <li>intel core</li>
        </ui>
        <div>
          <div><?= $product->getPrice()?></div>
          <div><a>Customize</a></div>
        </div>
      </div>
    <?php endforeach;?>
  </div> 
</div>


